setwd("~/R/Springboard-Section7/Clustering")

flower = read.csv("flower.csv", header = FALSE)
str(flower)
as.matrix(flower)
flowerMatrix = as.matrix(flower)
str(flowerMatrix)
flowerVector = as.vector(flowerMatrix)
str(flowerVector)
flowerVector2 = as.vector(flower)
str(flowerVector2)
distance = dist(flowerVector, method = "euclidean")
str(distance)
clusterIntensity = hclust(distance, method = "ward")
plot(clusterIntensity)
rect.hclust(clusterIntensity, k = 3, border = "Red")
flowerClusters = cutree(clusterIntensity, k=3)
flowerClusters
tapply(flowerVector, flowerClusters, mean)
dim(flowerClusters) = c(50,50)
image(flowerClusters, axes = FALSE)
image(flowerMatrix, axes = FALSE, col = grey(seq(0,1,length=256)))
